### ISSUE TITLE
Failed to activate the html-to-string package

### ISSUE THREAD

**Issue by q13** [nakajmg/atom-html-to-string#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.4
**System**: Ubuntu 14.04.3
**Thrown From**: [html-to-string](https://github.com/nakajmg/atom-html-to-string) package, v0.2.3
### Stack Trace

Failed to activate the html-to-string package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/home/q13/.atom/packages/html-to-string/lib/html-to-string.coffee:3:23)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:243:19)
  at /usr/share/atom/resources/app.asar/src/package.js:836:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -0:12.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:12.6.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:12.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:12.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:12.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:12.4.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:12.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:12.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:12.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:12.1.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:12.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:11.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:11.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:11.5.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:11.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:00.6.0 htmlToString:convert (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "save-session"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.8
atom-ternjs, v0.7.1
docblockr, v0.7.3
emmet, v2.3.12
file-icons, v1.6.2
html-to-string, v0.2.3
linter, v1.3.0
linter-htmlhint, v0.0.17
linter-jshint, v1.1.4
linter-jsxhint, v0.1.2
local-history, v3.2.3
minimap, v4.12.2
react, v0.12.6

# Dev
No dev packages
```

**Comment by radarsu** [comment]
Same here. When trying to convert html to string.

**Comment by radarsu** [comment]
Same here, when trying to convert.

**Comment by vicrec** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [html-to-string](https://github.com/nakajmg/atom-html-to-string) package, v0.2.3

### Stack Trace

Failed to activate the html-to-string package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (file:///C:/Users/vit.reccia/.atom/packages/html-to-string/lib/html-to-string.coffee:3:23)
    at Package.module.exports.Package.activateNow (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\src\package.js:170:19)
    at C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\src\package.js:740:25
    at Emitter.module.exports.Emitter.emit (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\src\command-registry.js:241:20)
    at C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\vit.reccia\Downloads\atom-windows\Atom\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:15.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:13 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13 htmlToString:convert (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "atom-autocomplete-php"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.3.1
color-picker-service, v0.0.1
html-id-class-snippets, v1.4.1
html-to-string, v0.2.3
jquery-snippets, v11.0.0
nuclide-fuzzy-filename-provider, vundefined
nuclide-quick-open, v0.0.35
nuclide-remote-projects, v0.0.35
nuclide-toolbar, v0.0.35
remote-sync, v3.5.0
tool-bar, v0.1.9
webbox-color, v0.5.9

# Dev
No dev packages
```

---

Same error here too.

**Comment by nxz91** [comment]
+1
