### ISSUE TITLE
Failed to activate the html-to-string package

### ISSUE THREAD

**Issue by xiamu14** [nakajmg/atom-html-to-string#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [html-to-string](https://github.com/nakajmg/atom-html-to-string) package, v0.2.3
### Stack Trace

Failed to activate the html-to-string package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (file:///D:/S/atom/.atom/packages/atom-html-to-string/lib/html-to-string.coffee:3:23)
    at Package.module.exports.Package.activateNow (D:\S\atom\app-1.7.3\resources\app.asar\src\package.js:183:20)
    at D:\S\atom\app-1.7.3\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (D:\S\atom\app-1.7.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (D:\S\atom\app-1.7.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\S\atom\app-1.7.3\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (D:\S\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (D:\S\atom\app-1.7.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (D:\S\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (D:\S\atom\app-1.7.3\resources\app.asar\src\application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -0:03.4.0 htmlToString:convert (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "mypackage",
      "terminal-plus"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
file-icons, v1.7.11
pretty-json, v1.1.0

# Dev
No dev packages
```

**Comment by nxz91** [comment]
+1

**Comment by sjbwylbs** [comment]
+1

**Comment by shawnzhesun** [comment]
Since no one is maintaining this package, I adopted it and fixed this issue in this batch:
https://github.com/shawnzhesun/atom-HTML-Stringifier

**Comment by ChadRidings** [comment]
Thank you @shawnzhesun ... works great, much appreciated.
